services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Analytics\SiteId\SiteIdProvider: ~


    #
    # GOOGLE
    #

    Pimcore\Analytics\Google\Config\ConfigProvider: ~
    Pimcore\Analytics\Google\Config\Config:
        factory: ['@Pimcore\Analytics\Google\Config\ConfigProvider', 'getConfig']

    Pimcore\Analytics\Google\Config\SiteConfigProvider: ~

    Pimcore\Analytics\Google\Tracker:
        calls:
            - [setLogger, ['@logger']]
